# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: advent
version: '0.0.0'
github: "Yury-Zakharov/advent"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: advent is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - containers
  - pureMD5
  - bytestring
  source-dirs: library

executables:
  advent:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - advent
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  advent-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - advent
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  advent-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - advent
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
